name = 'standard'

dice = [

  # note this is a specific ordering
  9,
  5,
  2,
  6,
  3,
  8,
  10,
  12,
  11,
  4,
  8,
  10,
  9,
  4,
  5,
  6,
  3,
  11,

]

topology = [

  # row 1
  { coords = { x = 1, y = -1, z = 0 }, isOcean = true },
  { coords = { x = 2, y = -2, z = 0 }, isOcean = true },
  { coords = { x = 3, y = -3, z = 0 }, isOcean = true },
  { coords = { x = 4, y = -4, z = 0 }, isOcean = true },

  # row 2
  { coords = { x = 0, y = -1, z = 1 }, isOcean = true },
  { coords = { x = 1, y = -2, z = 1 }, isOcean = false, resources = '*' },
  { coords = { x = 2, y = -3, z = 1 }, isOcean = false, resources = '*' },
  { coords = { x = 3, y = -4, z = 1 }, isOcean = false, resources = '*' },
  { coords = { x = 4, y = -5, z = 1 }, isOcean = true },

  # row 3
  { coords = { x = -1, y = -1, z = 2 }, isOcean = true },
  { coords = { x = 0, y = -2, z = 2 }, isOcean = false, resources = '*' },
  { coords = { x = 1, y = -3, z = 2 }, isOcean = false, resources = '*' },
  { coords = { x = 2, y = -4, z = 2 }, isOcean = false, resources = '*' },
  { coords = { x = 3, y = -5, z = 2 }, isOcean = false, resources = '*' },
  { coords = { x = 4, y = -6, z = 2 }, isOcean = true },

  # row 4
  { coords = { x = -2, y = -1, z = 3 }, isOcean = true },
  { coords = { x = -1, y = -2, z = 3 }, isOcean = false, resources = '*' },
  { coords = { x = 0, y = -3, z = 3 }, isOcean = false, resources = '*' },
  { coords = { x = 1, y = -4, z = 3 }, isOcean = false, resources = '*' },
  { coords = { x = 2, y = -5, z = 3 }, isOcean = false, resources = '*' },
  { coords = { x = 3, y = -6, z = 3 }, isOcean = false, resources = '*' },
  { coords = { x = 4, y = -7, z = 3 }, isOcean = true },

  # row 5
  { coords = { x = -2, y = -2, z = 4 }, isOcean = true },
  { coords = { x = -1, y = -3, z = 4 }, isOcean = false, resources = '*' },
  { coords = { x = 0, y = -4, z = 4 }, isOcean = false, resources = '*' },
  { coords = { x = 1, y = -5, z = 4 }, isOcean = false, resources = '*' },
  { coords = { x = 2, y = -6, z = 4 }, isOcean = false, resources = '*' },
  { coords = { x = 3, y = -7, z = 4 }, isOcean = true },

  # row 6
  { coords = { x = -2, y = -3, z = 5 }, isOcean = true },
  { coords = { x = -1, y = -4, z = 5 }, isOcean = false, resources = '*' },
  { coords = { x = 0, y = -5, z = 5 }, isOcean = false, resources = '*' },
  { coords = { x = 1, y = -6, z = 5 }, isOcean = false, resources = '*' },
  { coords = { x = 2, y = -7, z = 5 }, isOcean = true },

  # row 7
  { coords = { x = -2, y = -4, z = 6 }, isOcean = true },
  { coords = { x = -1, y = -5, z = 6 }, isOcean = true },
  { coords = { x = 0, y = -6, z = 6 }, isOcean = true },
  { coords = { x = 1, y = -7, z = 6 }, isOcean = true },

]

ports = [

  { hex = { orientation = 1, coords = { x = 3, y = -4, z = 1 }, }, orientation = [10, 4], type = 'wheat' },
  { hex = { orientation = 3, coords = { x = 3, y = -5, z = 2 }, }, orientation = [12, 6], type = 'wood' },
  { hex = { orientation = 3, coords = { x = 2, y = -6, z = 4 }, }, orientation = [12, 6], type = 'sheep' },
  { hex = { orientation = 5, coords = { x = 1, y = -6, z = 5 }, }, orientation = [2, 8], type = 'mystery' },
  { hex = { orientation = 5, coords = { x = -1, y = -4, z = 5 }, }, orientation = [2, 8], type = 'mystery' },
  { hex = { orientation = 7, coords = { x = -1, y = -3, z = 4 }, }, orientation = [4, 10], type = 'brick' },
  { hex = { orientation = 9, coords = { x = -1, y = -2, z = 3 }, }, orientation = [6, 12], type = 'mystery' },
  { hex = { orientation = 11, coords = { x = 0, y = -2, z = 2 }, }, orientation = [8, 2], type = 'ore' },
  { hex = { orientation = 1, coords = { x = 1, y = -2, z = 1 }, }, orientation = [10, 4], type = 'mystery' },

]

[buyable]

  [buyable.road]
  name = 'road'
  maxNum = 15
  cost = { brick = 1, wood = 1 }

  [buyable.settlement]
  name = 'settlement'
  maxNum = 5
  cost = { wheat = 1, sheep = 1, brick = 1, wood = 1 }

  [buyable.city]
  name = 'city'
  maxNum = 4
  cost = { ore = 3, wheat = 2 }

  [buyable.devCard]
  name = 'development card'
  maxNum = 25
  cost = { ore = 1, wheat = 1, sheep = 1 }

[devCards]

  vp = 5
  knight = 14
  monopoly = 2
  rb = 2
  yop = 2

[resources]

  ore = 3
  wheat = 4
  sheep = 4
  brick = 3
  wood = 4
  desert = 1
  ocean = 18
